version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    ports:
      - "8888:80"
    depends_on:
      - app
    networks:
      - mynetwork

  app:
    build: .
    command: uvicorn app.fastapi_app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - /database/db/:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
