version: '3.2'
services:
  web:
    build:
      context: .
    stop_signal: SIGKILL
    ports:
      - 80:80
    networks:
      - mynetwork
    depends_on:
      - postgres


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /database/db/:/var/lib/postgresql/data
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
