version: '3.2'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    networks:
      - mynetwork
    volumes:
      - nginx.conf /etc/nginx/nginx.conf

  app:
    build:
      context: .
    stop_signal: SIGKILL
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /database/db/:/var/lib/postgresql/data
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
